language: objective-c
rvm: 1.9.3
before_install:
  - pod install
  - export LANG=en_US.UTF-8
  - brew update
  - brew uninstall xctool
  - brew install xctool
  - brew install shenzhen

xcode_workspace: TravisTest.xcworkspace
xcode_scheme: TravisTest
xcode_sdk: iphonesimulator

notifications:
  email:
    - sergey@alterplay.com