language: objective-c
xcode_scheme: TravisTest

before_install:
        - sudo gem update --system
        - sudo gem install cocoapods
        - sudo gem install ios_ci
        - brew install ios-sim
        - cd Spec
        - pod 
        
