language: objective-c
xcode_scheme: TravisTest

before_install:
        - sudo gem update --system
        - sudo gem install cocoapods
        - pod install
        
notifications:
  email:
    - sergey@alterplay.com
