language: objective-c
xcode_scheme: TravisTest

before_install:
        - sudo gem update --system
        - sudo gem install cocoapods
	- brew install ios-sim
        - pod install
        
script:
        - xcodebuild test -workspace TravisTest.xcworkspace -scheme TravisTest -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
        
notifications:
  email:
    - sergey@alterplay.com
