language: objective-c
rvm: 1.9.3
before_install:
  - pod install
  - export LANG=en_US.UTF-8
  - brew update
  - brew uninstall xctool
  - brew install xctool

script:
  - xctool test -workspace TravisTest.xcworkspace -scheme TravisTest -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

notifications:
  email:
    recipients:
      - sergey@alterplay.com
    on_success: change
    on_failure: always