language: objective-c
rvm: 1.9.3
before_install:
  - gem install cocoapods
  - pod install
  - export LANG=en_US.UTF-8
  - brew update
  - brew uninstall xctool
  - brew install xctool

xcode_workspace: TravisTest.xcworkspace
xcode_scheme: TravisTest
xcode_sdk: iphonesimulator
