
  pod 'APCDController'
  pod 'TestFlightSDK'
  pod 'UIColor-HexString'
  pod 'UIColor-Utilities'
  pod 'FrameAccessor'
  pod 'UIAlertView+Blocks'
  pod 'UIActionSheet+Blocks'
  pod 'SDWebImage'
  pod 'ZipArchive'
  pod 'CocoaSoundCloudAPI'
  pod 'pop', '~> 1.0'
  pod 'POP+MCAnimate', '~> 2.0'
  pod 'AHEasing', '~> 1.2'
  pod 'BlocksKit', '~> 2.2.5'
  pod 'FMDB/FTS'
  pod 'EasyMapping', '~> 0.6.3'
  pod 'FXBlurView'
  pod 'macros_blocks', '~> 0.0.3'
  pod 'HockeySDK', '~> 3.6.1'
  pod 'Shapes', '~> 1.0.0'
  pod 'PHFDelegateChain', '~> 1.0.1'
  pod 'SSPullToRefresh', '~> 1.2.2'
  pod 'SCSiriWaveformView', '~> 1.0.1'